title: Adversarial attacks on machine learning
author: Ajith Kanumuri
email: saiajith25@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am doing a course on GitHub Learning Lab and this is a practice website.

# social links
twitter_username: ajith1411 # DO NOT include the @ character, or else the build will fail!
github_username:  ajith05 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
